backend:
  name: git-gateway
  branch: dev

media_folder: _data/media

collections:
  - name: "settings"
    label: "Settings"
    delete: false # Prevent users from deleting documents in this collection
    editor:
      preview: false
    files:
      - name: "general"
        label: "Site Settings"
        file: "_data/settings.json"
        fields:
          - { label: "Global title", name: "site_title", widget: "string" }
          - label: "PDFs Resumés"
            name: resume
            widget: "object"
            fields:
              - { label: "Single Page Resumé", name: "name", widget: "string" }
              - { label: "Full Resumé", name: "full_resume", widget: "string" }
          - label: "Social Medias"
            label_singular: "Social"
            name: "social"
            widget: list
            fields:
              - { label: "Name", name: "name", widget: "string" }
              - { label: "Hover", name: "hover", widget: "string" }
              - { label: "Link", name: "link", widget: "string" }
      - name: "menu"
        label: "Menu Settings"
        file: "_data/menu.json"
        fields:
          - label: "Menu item"
            name: "menuitem"
            label_singular: "Menu item"
            widget: list
            fields:
              - { label: "Title", name: "name", widget: "string" }
              - { label: "URL", name: "url", widget: "string" }
