backend:
  name: git-gateway
  branch: dev

media_folder: public/_data/media

collections:
  - name: "settings"
    label: "Settings"
    delete: false # Prevent users from deleting documents in this collection
    editor:
      preview: false
    files:
      - name: "general"
        label: "Site Settings"
        file: "public/_data/settings.json"
        fields:
          - { label: "Global title", name: "site_title", widget: "string" }
      - name: "socialmedia"
        label: "Social Media Settings"
        file: "public/_data/socialmedia.json"
        fields:
          - label: "Social Network"
            name: "socialitem"
            widget: list
            fields:
              - { label: "Name", name: "name", widget: "string" }
              - { label: "Hover", name: "hover", widget: "string" }
              - { label: "URL", name: "url", widget: "string" }
      - name: "menu"
        label: "Menu Settings"
        file: "public/_data/menu.json"
        fields:
          - label: "Menu item"
            name: "menuitem"
            widget: list
            fields:
              - { label: "Title", name: "name", widget: "string" }
              - { label: "URL", name: "url", widget: "string" }
  - name: "home"
    label: "Home page"
    delete: false # Prevent users from deleting documents in this collection
    editor:
      preview: false
    files:
      - name: "homecontent"
        label: "Home Content"
        file: "public/_data/home.json"
        fields:
          - { label: "Home title", name: "title", widget: "string" }
          - { label: "Home subtitle", name: "subtitle", widget: "markdown" }
          - { label: "Home content", name: "content", widget: "markdown" }
          - { label: "Home image", name: "image", widget: "image" }
          - label: "Home links"
            name: "links"
            widget: list
            fields:
              - { label: "Title", name: "name", widget: "string" }
              - { label: "URL", name: "url", widget: "string" }
  - name: "resume"
    label: "Resumé page"
    delete: false # Prevent users from deleting documents in this collection
    editor:
      preview: false
    files:
      - name: "resumecontent"
        label: "Resumé Content"
        file: "public/_data/resume.json"
        fields:
          - { label: "Resume title", name: "title", widget: "string" }
          - label: "About me"
            name: about
            widget: "object"
            fields:
              - { label: "About Me title", name: "title", widget: "string" }
              - { label: "About Me content", name: "content", widget: "markdown" }
              - { label: "About Me image", name: "image", widget: "image" }
          - label: "PDFs Resumés"
            name: resume
            widget: "object"
            fields:
              - { label: "Single Page Resumé", name: "name", widget: "string" }
              - { label: "Full Resumé", name: "full_resume", widget: "string" }
          - label: "Education"
            name: education
            widget: "object"
            fields:
              - { label: "Education title", name: "education_title", widget: "string" }
              - label: "Education item"
                widget: list
                name: education_items
                fields:
                  - { label: "Title", name: "title", widget: "string" }
                  - { label: "Institution", name: "institution", widget: "string" }
                  - { label: "Link", name: "link", widget: "string" }
                  - { label: "Finished", name: "finished", widget: "string" }
          - label: "Skills"
            name: skills
            widget: "object"
            fields:
              - { label: "Skills title", name: "skills_title", widget: "string" }
              - label: "Categories"
                name: categories
                widget: list
                fields:
                  - { label: "Category title", name: "category_title", widget: "string" }
                  - label: "Category"
                    name: category
                    widget: list
                    fields:
                      - { label: "Skill", name: "name", widget: "string" }
                      - { label: "Percentage", name: "percentage", widget: "number", required: false }
          - label: "Experience"
            name: experience
            widget: "object"
            fields:
              - { label: "Experience title", name: "experience_title", widget: "string" }
              - label: "Job item"
                widget: list
                name: job
                fields:
                  - { label: "Company", name: "company", widget: "string" }
                  - { label: "Position", name: "position", widget: "string" }
                  - { label: "From", name: "from", widget: "string" }
                  - { label: "To", name: "to", widget: "string" }
                  - { label: "Description", name: "description", widget: "markdown" }
  - name: "mystory"
    label: "My Story page"
    delete: false # Prevent users from deleting documents in this collection
    editor:
      preview: false
    files:
      - name: "mystorycontent"
        label: "My Story Content"
        file: "public/_data/story.json"
        fields:
          - label: "Story"
            name: story
            widget: list
            fields:
              - { label: "Title", name: "title", widget: "string" }
              - { label: "Subtitle", name: "subtitle", widget: "string" }
              - { label: "Song", name: "song", widget: "string" }
              - { label: "Content", name: "content", widget: "markdown" }
              - { label: "Color", name: "color", widget: "string" }
              - { label: "Image", name: "image", widget: "image" }
              - { label: "Image alt", name: "alt", widget: "string" }
  - name: "portfolio"
    label: "Portfolio page"
    delete: false # Prevent users from deleting documents in this collection
    editor:
      preview: false
    files:
      - name: "portfoliocontent"
        label: "Portfolio Content"
        file: "public/_data/portfolio.json"
        fields:
          - label: "Portfolio"
            name: "portfolio"
            widget: "object"
            fields:
              - { label: "Portfolio title", name: "title", widget: "string" }
              - { label: "Portfolio content", name: "content", widget: "markdown" }
              - label: "Projects"
                name: "projects"
                widget: list
                fields:
                  - { label: "Project Title", name: "title", widget: "string" }
                  - { label: "Project Content", name: "content", widget: "markdown" }
                  - { label: "Project Cover image", name: "image", widget: "image" }
                  - { label: "Project File location", name: "file", widget: "string" }
